# Generated by Django 5.1.6 on 2025-03-13 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0002_menuitems_delete_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitems',
            old_name='course',
            new_name='category',
        ),
    ]
