# Generated by Django 5.1.6 on 2025-03-13 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0003_rename_course_menuitems_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitems',
            old_name='name',
            new_name='itemname',
        ),
    ]
