# Generated by Django 4.1.3 on 2025-03-24 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='menu_id',
            new_name='menuitem_id',
        ),
    ]
