# Generated by Django 5.1.7 on 2025-03-25 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='Title',
            new_name='title',
        ),
    ]
