# Generated by Django 5.1.6 on 2025-03-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='descriptiion',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
