# Generated by Django 5.1.6 on 2025-03-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_descriptiion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='descriptiion',
            new_name='description',
        ),
    ]
