# Generated by Django 5.1.7 on 2025-03-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookListAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['price'], name='BookListAPI_price_779a55_idx'),
        ),
    ]
